---
ansible_host: 192.168.1.203
ansible_user: root


# ---------------------------------------
#  backup playbook variables
# ---------------------------------------
backup_create_archive: no
backup_script_cmd: scripts/grafana_dashboards_backup.py -a {{ grafana_api_key }}
backup_archive: /root/backups/*.tgz
backup_target_user: metrics
backup_target_dir: /mnt/pool/backups/CONTAINERS/metrics/
