---
ansible_host: 192.168.1.209
ansible_user: jacob


# ---------------------------------------
#  deployment role variables
# ---------------------------------------
deployment_hostname: docker-ubuntu
deployment_static_ip: 192.168.1.209


# ---------------------------------------
#  backup playbook variables
# ---------------------------------------
backup_source_become: yes
backup_source_dir: /home/jacob/volumes
backup_archive: /tmp/docker_{{ ansible_date_time.iso8601_basic_short }}.tgz
backup_target_user: docker
backup_target_dir: /mnt/pool/backups/CONTAINERS/docker/
