---
ansible_host: 192.168.1.132
ansible_user: jacob


# ---------------------------------------
#  deployment role variables
# ---------------------------------------
deployment_hostname: gothmog
deployment_static_ip: 192.168.1.132
