---
ansible_host: 192.168.1.214
ansible_user: root


# ---------------------------------------
#  backup playbook variables
# ---------------------------------------
backup_create_archive: no
backup_script_cmd: scripts/bitwarden_vault_backup.py -u {{ bitwarden_username }} -p {{ bitwarden_password }}
backup_archive: /root/backups/*
backup_target_user: bitwarden
backup_target_dir: /mnt/pool/backups/CONTAINERS/bitwarden/
