---
all:
  children:
    pi:
      hosts:
        glaurung:
        ungoliant:
    debian:
      hosts:
        gothmog:
      children:
        sauron_vms:
          hosts:
            ansible_controller:
            docker:
            lamp:
            gitea:
            plex:
    arch:
      hosts:
        sigurd:
    new:
      hosts:
          192.168.1.42:
