---
- name: Set IP to Static
  become: true
  replace:
    path: /etc/network/interfaces
    regexp: 'dhcp'
    replace: 'static'

- name: Define Static Addresses
  become: true
  blockinfile:
    path: /etc/network/interfaces
    block: |
        address {{ deployment_static_ip }}
        netmask 255.255.255.0
        gateway 192.168.1.1
