---
- name: Get network interface name
  set_fact:
    interface: "{{ ansible_facts.interfaces | map('extract', ansible_facts) | list
                  | selectattr('ipv4', 'defined')
                  | selectattr('ipv4.address', 'equalto', ansible_host)
                  | map(attribute='device') | first }}"
  failed_when: interface | length == 0

- name: Set Static IP
  become: true
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
        interface {{ interface }}
        static ip_address={{ deployment_static_ip }}
        static routers=192.168.1.1
        static domain_name_servers=192.168.1.1
