---
- name: Install ssh
  command: pct exec {{ deployment_container_id }} -- dnf install openssh-server -y
  changed_when: yes

- name: Enable root login
  command: pct exec {{ deployment_container_id }} -- sed -i 's/.*PermitRootLogin.*/PermitRootLogin yes/g' /etc/ssh/sshd_config
  changed_when: yes

- name: Start ssh service
  command: pct exec {{ deployment_container_id }} -- systemctl enable --now sshd
  changed_when: yes
