---
- hosts: new
  gather_facts: no

  vars_prompt:
    - name: static_ip
      prompt: What is the new static ip?
      private: no
    - name: hostname
      prompt: What is the new hostname?
      private: no

  vars:
    playbook_type: debian

  module_defaults:
    apt:
      force_apt_get: yes

  handlers:
    - import_tasks: handlers/update_dotfiles.yml

  tasks:
    - include: tasks/bootstrap_python.yml
    - include: tasks/copy_ansible_ssh_key.yml
    - include: tasks/setup_ssh.yml
    - include: tasks/set_locale.yml
    - include: tasks/apt_upgrade.yml
    - include: tasks/apt_install_packages.yml
    - include: tasks/install_vundle.yml
    - include: tasks/deploy_dotfiles.yml
    - include: tasks/set_ip_debian.yml
    - include: tasks/set_hostname.yml

    - meta: flush_handlers

    - name: Reboot Machine
      become: true
      command: shutdown -r 1
