---
ansible_host_key_checking: False
ansible_ssh_host_key_checking: False
ansible_paramiko_host_key_checking: False

ansible_ssh_password: "{{ ansible_become_pass }}"
ansible_password: "{{ ansible_become_pass }}"
